// Notebook actions
export const NEW_NOTEBOOK_REQUEST = "NEW_NOTEBOOK_REQUEST";
export const NEW_NOTEBOOK_SUCCESS = "NEW_NOTEBOOK_SUCCESS";
export const NEW_NOTEBOOK_FAILURE = "NEW_NOTEBOOK_FAILURE";
export const NEW_NOTEBOOK_RESET = "NEW_NOTEBOOK_RESET";

export const GET_NOTEBOOKS_REQUEST = "GET_NOTEBOOKS_REQUEST";
export const GET_NOTEBOOKS_SUCCESS = "GET_NOTEBOOKS_SUCCESS";
export const GET_NOTEBOOKS_FAILURE = "GET_NOTEBOOKS_FAILURE";

export const GET_NOTEBOOK_REQUEST = "GET_NOTEBOOK_REQUEST";
export const GET_NOTEBOOK_SUCCESS = "GET_NOTEBOOK_SUCCESS";
export const GET_NOTEBOOK_FAILURE = "GET_NOTEBOOK_FAILURE";

export const UPDATE_NOTEBOOK_REQUEST = "UPDATE_NOTEBOOK_REQUEST";
export const UPDATE_NOTEBOOK_SUCCESS = "UPDATE_NOTEBOOK_SUCCESS";
export const UPDATE_NOTEBOOK_FAILURE = "UPDATE_NOTEBOOK_FAILURE";

export const DELETE_NOTEBOOK_REQUEST = "DELETE_NOTEBOOK_REQUEST";
export const DELETE_NOTEBOOK_SUCCESS = "DELETE_NOTEBOOK_SUCCESS";
export const DELETE_NOTEBOOK_FAILURE = "DELETE_NOTEBOOK_FAILURE";

// Note actions
export const NEW_NOTE_REQUEST = "NEW_NOTE_REQUEST";
export const NEW_NOTE_SUCCESS = "NEW_NOTE_SUCCESS";
export const NEW_NOTE_FAILURE = "NEW_NOTE_FAILURE";

export const GET_NOTE_REQUEST = "GET_NOTE_REQUEST";
export const GET_NOTE_SUCCESS = "GET_NOTE_SUCCESS";
export const GET_NOTE_FAILURE = "GET_NOTE_FAILURE";

export const UPDATE_NOTE_REQUEST = "UPDATE_NOTE_REQUEST";
export const UPDATE_NOTE_SUCCESS = "UPDATE_NOTE_SUCCESS";
export const UPDATE_NOTE_FAILURE = "UPDATE_NOTE_FAILURE";

export const DELETE_NOTE_REQUEST = "DELETE_NOTE_REQUEST";
export const DELETE_NOTE_SUCCESS = "DELETE_NOTE_SUCCESS";
export const DELETE_NOTE_FAILURE = "DELETE_NOTE_FAILURE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
